env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - standard-with-typescript
  - plugin:prettier/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - "./tsconfig.json"
plugins:
  - vue
rules:
  no-undef: off
  "@typescript-eslint/explicit-function-return-type": off
overrides:
  - files:
    - 'pages/**/*.vue'
    - 'layouts/**/*.vue'
    rules:
      vue/multi-word-component-names: off
