env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - "./tsconfig.json"
plugins:
  - vue
rules: {}
overrides:
  - files:
    - 'pages/**/*.vue'
    rules:
      vue/multi-word-component-names: off
